### ISSUE TITLE
private key revealed

### ISSUE THREAD

**Issue by renepickhardt** [jarret/mock-c-lightning#1]
https://github.com/jarret/mock-c-lightning/blob/86166039935a0ea4e5b1aa9308665d414e7d664e/mock-c-lightning.py#L17

should probably load that from a config file

**Comment by jarret** [comment]
This wasn't really intended as a secret private key - just the key that signs the bolt11.
In any case, I renamed it to `SIGNING_KEY` and made the value something that is more obviously non-random
https://github.com/jarret/mock-c-lightning/blob/bca11227d8c33ec5af23c7a6a291bdb57fe6b60b/mock-c-lightning.py#L18

Also, recent update overhauls it to be wrapped in an object and adds more features and documentation to the `README.md`
